name: Setup
description: Setup Environment
inputs:
  python-version:
    type: string
    required: true
  caller-is-kiss-cf:
    type: string
    required: false
    default: 'no'
  kiss-cf-token:
    required: false


runs:
  using: "composite"

  steps:
  # COMMON steps
    - name: set up python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: upgrade python (Win+Linux)
      run: python -m pip install --upgrade pip
      shell: bash

    # checkout repositories
    - name: Checkout
      uses: actions/checkout@v3
    # note: requirements are not installed since this is handled by TOX within
    # the venv

    # handle kiss_cf repository
    - name: Checkout kiss_cf (if called from using project)
      uses: actions/checkout@v3
      with:
        repository: alexander-rd/kiss_cf
        path: kiss_cf
        # TODO: remove token once repo becomes public
        token: ${{ inputs.kiss-cf-token }}
      if: inputs.caller-is-kiss-cf == 'no'
    # install kiss_cf repository
    - name: Install kiss_cf (if called from using project)
      run: pip install -e./kiss_cf
      shell: bash
      if: inputs.caller-is-kiss-cf == 'no'

  # LINUX specific steps
    - name: Install tkinter
      run: sudo apt install python3-tk
      shell: bash
      if: runner.os == 'Linux'
    - name: Orientation (ls)
      run: ls -la
      shell: bash
      if: runner.os == 'Linux'

  # WINDOWS specific steps: none, yet

