# Copyright 2024-2026 the contributors of APPXF (github.com/alexander-nbg/appxf)
# SPDX-License-Identifier: 0BSD

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: '3.12'
  jobs:
    pre_build:
      - bash scripts/_ensure_plantuml_jar.sh
  apt_packages:
    - default-jre-headless

sphinx:
  configuration: doc/conf.py

python:
  install:
    - requirements: doc/requirements.txt
