@startuml
!include ../../style.puml

|User Application|
start
->UI opens;
if (admin keys) then (available)
:UI opens
(no load admin keys button);
else (missing)
:UI opens
(with load admin keys button);
endif;
stop
@enduml
