''' Registration Request based on bytes

The class RegistrationRequest serializes and deserializes a registration
request from user to admin. It is expected to be handled in an encrypted file
which is not in scope of this class.
'''
from __future__ import annotations

from typing import TypedDict, Any

from kiss_cf.security import Security
from kiss_cf.storage import serialize, deserialize


class RegistrationRequestData(TypedDict):
    version: int
    user_data: dict[str, Any]
    signing_key: bytes
    encryption_key: bytes
    test_blob: str
    test_signature: bytes
    test_encrypted: bytes


class RegistrationRequest:
    def __init__(self, data):
        ''' DO NOT USE directly

        Use either new() or from_bytes() class methods to construct a
        Registration Response'''
        self._data = data

    @property
    def signing_key(self):
        return self._data['signing_key']

    @property
    def encryption_key(self):
        return self._data['encryption_key']

    @property
    def user_data(self):
        return self._data['user_data']

    @classmethod
    def new(cls,
            user_data: dict[str, Any],
            security: Security) -> RegistrationRequest:
        ''' Generate a new RegistrationResponse from data

        Arguments:
            user_data -- USER section of configuration
            security -- User's Security object

        Returns:
            constructed RegistrationRequest class
        '''
        data: RegistrationRequestData = {
            'version': 1,
            'user_data': user_data,
            'signing_key': security.get_signing_public_key(),
            'encryption_key': security.get_encryption_public_key(),
            'test_blob': 'hello',
            'test_signature': security.sign(b'hello'),
            'test_encrypted': b'hello',
            }
        # TODO: no option to test encryption key (on this path) since there is
        # no encryption based on the private key.
        return cls(data)

    @classmethod
    def from_request(cls, request_bytes: bytes):
        ''' Generate a RegistrationResponse from bytes

        The bytes must have been generated by RegistrationResponse of the same
        version.

        Arguments:
            registration_bytes -- USER section of configuration
            security -- User's Security object

        Returns:
            constructed RegistrationRequest class
        '''
        data = deserialize(request_bytes)
        return cls(data)

    def get_request_bytes(self) -> bytes:
        ''' Get serialized bytes for sending to admin '''
        # TODO: verify signing key
        return serialize(self._data)
