' Copyright 2026 the contributors of APPXF (github.com/alexander-nbg/appxf)
' SPDX-License-Identifier: 0BSD
@startuml
!include ../../style.puml

|Application|
start
:<b>workflows/test.yml</b>;
|APPXF|
:<b>actions/setup/action.yml</b>(python version)
Plus appxf token as long as not appxf;

|Application|
:<b>actions/setup/action.yml</b>
(optional) for application
specific installations;

|APPXF|
:<b>.github/actions/run-tox</b>
Install, cache venv and run tox.;
|Application|
end
@enduml
