' Copyright 2026 the contributors of APPXF (github.com/alexander-nbg/appxf)
' SPDX-License-Identifier: 0BSD
@startuml
!include ../../style.puml

|User Application|
:generate request;
->send via email;

|Admin Application|
:review request
add to user database
generate response;
->send via email;

|User Application|
:load response;

@enduml
