# Copyright 2024-2026 the contributors of APPXF (github.com/alexander-nbg/appxf)
# SPDX-License-Identifier: Apache-2.0
"""Registration Request based on bytes

The class RegistrationRequest serializes and deserializes a registration
request from user to admin. It is expected to be handled in an encrypted file
which is not in scope of this class.
"""

from __future__ import annotations

from typing import Any, TypedDict

from appxf.security import Security
from appxf.storage import CompactSerializer

# TODO: apply DictStorable here bute keep the get_bytes interface.


class RegistrationRequestData(TypedDict):
    version: int
    user_data: dict[str, Any]
    signing_key: bytes
    encryption_key: bytes


class RegistrationRequest:
    def __init__(self, data, **kwargs):
        """DO NOT USE directly

        Use either new() or from_bytes() class methods to construct a
        Registration Response"""
        super().__init__(**kwargs)
        self._data = data

    @property
    def signing_key(self):
        return self._data["signing_key"]

    @property
    def encryption_key(self):
        return self._data["encryption_key"]

    @property
    def user_data(self):
        return self._data["user_data"]

    @classmethod
    def new(cls, user_data: dict[str, Any], security: Security) -> RegistrationRequest:
        """Generate a new RegistrationResponse from data

        Arguments:
            user_data -- USER section of configuration
            security -- User's security object to obtain
                singing/encryption keys.

        Returns:
            constructed RegistrationRequest class
        """
        data: RegistrationRequestData = {
            "version": 1,
            "user_data": user_data,
            "signing_key": security.get_signing_public_key(),
            "encryption_key": security.get_encryption_public_key(),
        }
        # TODO: no option to test encryption key (on this path) since there is
        # no encryption based on the private key.
        return cls(data)

    @classmethod
    def from_request(cls, request_bytes: bytes):
        """Generate a RegistrationResponse from bytes

        The bytes must have been generated by RegistrationResponse of the same
        version.

        Arguments:
            registration_bytes -- USER section of configuration
            security -- User's Security object

        Returns:
            constructed RegistrationRequest class
        """
        data = CompactSerializer.deserialize(request_bytes)
        return cls(data)

    def get_request_bytes(self) -> bytes:
        """Get serialized bytes for sending to admin"""
        return CompactSerializer.serialize(self._data)
